### ISSUE TITLE
Implement new $deprecated property

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/style-dictionary-utils#106]
There are now specs for the `$deprecated` property: https://github.com/design-tokens/community-group/pull/255#event-15447620289

Those are the specs:

### Deprecated

The **`$deprecated`** property MAY be used to mark a token as deprecated, and optionally explain the reason. Reasons to deprecate tokens include but are not limited to the following:

- A future update to the design system will remove this token
- Removing the token now may break existing support
- This token is discouraged from future use

<aside class="example">

```json
{
  "Button background": {
    "$value": "#777777",
    "$type": "color",
    "$deprecated": true
  },
  "Button focus": {
    "$value": "#70c0ff",
    "$type": "color",
    "$deprecated": "Please use the border style for active buttons instead."
  }
}
```

</aside>

| Value    | Explanation                                                 |
| :------- | :---------------------------------------------------------- |
| `true`   | This token is deprecated (no explanation provided).         |
| `String` | This token is deprecated AND this is an explanation.        |
| `false`  | This token is NOT deprecated (may override group defaults). |

Tool makers MAY augment the string when it contains aliases such as the one given as an example. A tool could potentially resolve the token, and link to docs, code, or render a visual representation of it and link to the new token inside a UI. For example, “Please use {button.activeBorder} instead“ could be output in JS as:

<aside class="example">

```js
/**
 * @deprecated Please use {@link file://./my-tokens.js:85 button.activeBorder} instead.
 */
```

</aside>

Or

<aside class="example">

```js
/**
 * @deprecated Please use {@link https://docs.ds/tokens/#button-activeborder button.activeBorder} instead.
 */
```

</aside>

# Tasks
- [ ] update the current tests for `isDeprecated` and  `commentDeprecated` so that they align with the new spec
- [ ] update the `isDeprecated` filter to align to the new specs, run the test for  isDeprecated and fix all bugs
- [ ] update the `commentDeprecated` transformer to align to the new specs, run the test for `commentDeprecated` and fix all bugs
