### ISSUE TITLE
Aligned layered shadows with w3c standard

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/style-dictionary-utils#107]
The w3c specs have been updated to include an updated spec for shadow tokens: https://github.com/design-tokens/community-group/pull/246

## This is the spec:

Shadow
Represents a shadow style. The $type property MUST be set to the string shadow. The value MUST contain a single object or an array of objects with the following properties:

color: The color of the shadow. The value of this property MUST be a valid [color value](https://github.com/design-tokens/community-group/blob/e4f734afb64bc5b48ab2340119709d73213250ac/technical-reports/format/composite-types.md#color) or a reference to a color token.
offsetX: The horizontal offset that shadow has from the element it is applied to. The value of this property MUST be a valid [dimension value](https://github.com/design-tokens/community-group/blob/e4f734afb64bc5b48ab2340119709d73213250ac/technical-reports/format/composite-types.md#dimension) or a reference to a dimension token.
offsetY: The vertical offset that shadow has from the element it is applied to. The value of this property MUST be a valid [dimension value](https://github.com/design-tokens/community-group/blob/e4f734afb64bc5b48ab2340119709d73213250ac/technical-reports/format/composite-types.md#dimension) or a reference to a dimension token.
blur: The blur radius that is applied to the shadow. The value of this property MUST be a valid [dimension value](https://github.com/design-tokens/community-group/blob/e4f734afb64bc5b48ab2340119709d73213250ac/technical-reports/format/composite-types.md#dimension) or a reference to a dimension token.
spread: The amount by which to expand or contract the shadow. The value of this property MUST be a valid [dimension value](https://github.com/design-tokens/community-group/blob/e4f734afb64bc5b48ab2340119709d73213250ac/technical-reports/format/composite-types.md#dimension) or a reference to a dimension token.
inset: (optional) Whether this shadow is inside the containing shape (“inner shadow”), rather than a “drop shadow” or “box shadow” which is rendered outside the container (default, or false).
{
  "shadow-token": {
    "$type": "shadow",
    "$value": {
      "color": "#00000080",
      "offsetX": "0.5rem",
      "offsetY": "0.5rem",
      "blur": "1.5rem",
      "spread": "0rem"
    }
  },
  "layered-shadow": {
    "$type": "shadow",
    "$value": [
      {
        "color": "#00000005",
        "offsetX": "0px",
        "offsetY": "24px",
        "blur": "22px",
        "spread": "0px"
      },
      {
        "color": "#0000000a",
        "offsetX": "0px",
        "offsetY": "42.9px",
        "blur": "44px",
        "spread": "0px"
      },
      {
        "color": "#0000000f",
        "offsetX": "0px",
        "offsetY": "64px",
        "blur": "64px",
        "spread": "0px"
      }
    ]
  },
  "inner-shadow": {
    "$type": "shadow",
    "$value": {
      "color": "#00000010",
      "offsetX": "2px",
      "offsetY": "2px",
      "blur": "4px",
      "spread": "0px",
      "inset": true
    }
  }
}

## Tasks
- [ ] update the tests to make sure the entire spec is covered
- [ ] update the transformer to make sure it strictly adheres to the updated specs
- [ ] run `npm test` and fix any issues until it passes
- [ ]
